Repository publiclab/image-sequencer, pull requests merged in 2018-10, with the labels that each got.

#362 refracted defaultHtmlStepUi.js
  examples/lib/defaultHtmlStepUi.js
Labels: ready-to-merge

#370 #363 Add placeholder option to input
  examples/lib/defaultHtmlStepUi.js
  src/modules/Brightness/info.json
Labels: ready-to-merge

#374 Add gamma module
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  src/Modules.js
  src/modules/GammaCorrection/Module.js
  src/modules/GammaCorrection/index.js
  src/modules/GammaCorrection/info.json
Labels: ready-to-merge

#384 adds default values to input fields for all module steps ( fixes #382 )
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  examples/lib/defaultHtmlStepUi.js
Labels: ready-to-merge

#396 Fixed the input.output mismatch bug in edge-detect module
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  src/modules/EdgeDetect/EdgeUtils.js
  src/modules/EdgeDetect/Module.js
Labels: ready-to-merge

#387 fix default parameters bug
  examples/lib/defaultHtmlStepUi.js
Labels: ready-to-merge

#394 enables Save button for an action when it is needed ( fixes #340 and #377 )
  examples/lib/defaultHtmlStepUi.js
Labels: ready-to-merge

#379 Updated index.html #378
  examples/index.html
Labels: ready-to-merge

#354 add histogram module
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  src/Modules.js
  src/modules/Histogram/Module.js
  src/modules/Histogram/index.js
  src/modules/Histogram/info.json
Labels: in progress

#414 add lock files
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  package-lock.json
  yarn.lock
Labels: in progress

#413 Update info.json #407
  src/modules/Blur/info.json
Labels: ready-to-merge

#410 removed typos as mentioned in issue #408
  src/modules/FisheyeGl/info.json
Labels: ready-to-merge

#411 Added scripts in package.json to fix installation
  README.md
  package.json
Labels: in progress, ready-to-merge

#331 Add manifest.json and cache static assets for offline use
  examples/demo.js
  examples/index.html
  examples/manifest.json
  examples/sw.js
  icons/ic_512.png
Labels: ready-to-merge

#446 Include a back-to-top Button on scrolling down
  examples/demo.css
  examples/index.html
  examples/lib/scrollToTop.js
Labels: ready-to-merge

#425 add demo files to npmignore
  .npmignore
Labels: in progress
