Repository publiclab/image-sequencer, pull requests merged in 2019-03, with the labels that each got.

#817 Update "Installation" section of README.md
  README.md
Labels: ready-to-merge

#696 Added New FlipImage Module
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  package-lock.json
  src/Modules.js
  src/modules/Blend/Module.js
  src/modules/FlipImage/Module.js
  src/modules/FlipImage/flipImage.js
  src/modules/FlipImage/index.js
  src/modules/FlipImage/info.json
Labels: needs-rebase, ready-to-merge

#754 Map types to html types
  dist/image-sequencer-ui.js
  dist/image-sequencer-ui.min.js
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  examples/lib/defaultHtmlStepUi.js
  examples/lib/mapHtmltypes.js
  src/Modules.js
  src/modules/Blend/info.json
  src/modules/Blur/info.json
  src/modules/Brightness/info.json
  src/modules/Colorbar/info.json
  src/modules/Contrast/info.json
  src/modules/Convolution/info.json
  src/modules/Crop/info.json
  src/modules/DecodeQr/info.json
  src/modules/DrawRectangle/info.json
  src/modules/Dynamic/info.json
  src/modules/EdgeDetect/info.json
  src/modules/GammaCorrection/info.json
  src/modules/Rotate/info.json
  src/modules/Saturation/info.json
  src/modules/WhiteBalance/info.json
Labels: enhancement, review-needed

#724 Add replace color module
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  src/Modules.js
  src/modules/ReplaceColor/Module.js
  src/modules/ReplaceColor/ReplaceColor.js
  src/modules/ReplaceColor/index.js
  src/modules/ReplaceColor/info.json
  test/core/modules/replace-color.js
Labels: module

#841 Document the new modules and docs-link for all modules
  docs/MODULES.md
  src/modules/AddQR/info.json
  src/modules/Average/info.json
  src/modules/Blend/info.json
  src/modules/Blur/info.json
  src/modules/Brightness/info.json
  src/modules/Channel/info.json
  src/modules/Colorbar/info.json
  src/modules/Colormap/info.json
  src/modules/Contrast/info.json
  src/modules/Convolution/info.json
  src/modules/Crop/info.json
  src/modules/DecodeQr/info.json
  src/modules/Dither/info.json
  src/modules/DrawRectangle/info.json
  src/modules/Dynamic/info.json
  src/modules/EdgeDetect/info.json
  src/modules/FisheyeGl/info.json
  src/modules/FlipImage/info.json
  src/modules/GammaCorrection/info.json
  src/modules/Gradient/info.json
  src/modules/Histogram/info.json
  src/modules/ImportImage/info.json
  src/modules/Invert/info.json
  src/modules/Ndvi/info.json
  src/modules/NdviColormap/info.json
  src/modules/Overlay/info.json
  src/modules/PaintBucket/info.json
  src/modules/ReplaceColor/info.json
  src/modules/Resize/info.json
  src/modules/Rotate/info.json
  src/modules/Saturation/info.json
  src/modules/Threshold/info.json
  src/modules/Tint/info.json
  src/modules/WhiteBalance/info.json
Labels: documentation, ready-to-merge

#824 Restructure API
  README.md
  dist/image-sequencer-ui.js
  dist/image-sequencer-ui.min.js
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  examples/demo.js
  examples/lib/defaultHtmlSequencerUi.js
  examples/lib/defaultHtmlStepUi.js
  examples/lib/insertPreview.js
  package-lock.json
  src/AddStep.js
  src/ExportBin.js
  src/FormatInput.js
  src/ImageSequencer.js
  src/InsertStep.js
  src/Run.js
  src/ui/LoadImage.js
  src/ui/UserInterface.js
  test/core/modules/QR.js
  test/core/modules/benchmark.js
  test/core/modules/brightness.js
  test/core/modules/chain.js
  test/core/modules/contrast.js
  test/core/modules/dynamic-imports.js
  test/core/modules/image-sequencer.js
  test/core/modules/import-export.js
  test/core/modules/invert.js
  test/core/modules/meta-modules.js
  test/core/modules/replace-color.js
  test/core/modules/replace.js
  test/core/modules/run.js
  test/core/modules/threshold.js
Labels: high-priority, performance, ready-to-merge, refactoring

#783 3.0.0
  package-lock.json
  package.json
Labels: important

#848 Change Footer Links In index.html
  examples/index.html
Labels: HTML, ready-to-merge, small, user-interface

#705 Centered the cropped image
  examples/demo.css
  examples/lib/defaultHtmlStepUi.js
Labels: enhancement, needs-rebase, ready-to-merge, user-interface

#752 Added tests for more modules
  test/core/modules/blur.js
  test/core/modules/channel.js
  test/core/modules/colormap.js
  test/core/modules/decode-qr.js
  test/core/modules/dither.js
  test/core/modules/resize.js
  test/core/modules/rotate.js
Labels: testing

#771 Complete Edge Detect Module
  dist/image-sequencer-ui.js
  dist/image-sequencer-ui.min.js
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  package-lock.json
  package.json
  src/modules/EdgeDetect/EdgeUtils.js
  src/modules/EdgeDetect/Module.js
  src/modules/EdgeDetect/info.json
Labels: important, module, ready-to-merge

#744 Update Readme.md that includes importJSON section
  .gitignore
  README.md
Labels: documentation

#750 Add search functionality in choose Module select
  dist/image-sequencer-ui.js
  dist/image-sequencer-ui.min.js
  examples/demo.js
  examples/index.html
  examples/lib/defaultHtmlSequencerUi.js
  examples/lib/intermediateHtmlStepUi.js
  examples/selectize.default.css
  package-lock.json
  package.json
Labels: new-feature, user-interface

#721 Add: Exposure Module
  Module.js
  dist/image-sequencer-ui.min.js
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  info.json
  src/Modules.js
  src/modules/Exposure/Module.js
  src/modules/Exposure/index.js
  src/modules/Exposure/info.json
Labels: module

#881 Add Dropdown Transitions
  dist/image-sequencer-ui.js
  examples/lib/defaultHtmlStepUi.js
Labels: ready-to-merge

#914 Seo tags for google search
  examples/index.html
Labels: ready-to-merge

#910 clear cache offline button
  examples/index.html
Labels: ready-to-merge

#908 gitignore dist and update links
  .gitignore
  .npmignore
  CONTRIBUTING.md
  README.md
  dist/image-sequencer-ui.min.js
  dist/image-sequencer.js
  dist/image-sequencer.min.js
Labels: ready-to-merge

#904 Improved Footer
  examples/index.html
Labels: ready-to-merge

#942 Bootstrap panel
  examples/demo.css
  examples/index.html
  examples/lib/defaultHtmlStepUi.js
Labels: ready-to-merge

#950 Fixed Typos in EdgeDetect/Module.js #884
  src/modules/EdgeDetect/Module.js
Labels: ready-to-merge
