Repository publiclab/image-sequencer, pull requests merged in 2019-04, with the labels that each got.

#655 Fix insert step and allow "closing" it
  examples/demo.css
  examples/demo.js
  examples/lib/defaultHtmlStepUi.js
  examples/lib/insertPreview.js
  examples/lib/intermediateHtmlStepUi.js
  package-lock.json
Labels: bug, user-interface

#967 Removed redundant parameters in ImageSequencer.js
  src/ImageSequencer.js
Labels: ready-to-merge

#996 More Modules option removed. Placeholder text added
  examples/demo.js
  examples/lib/intermediateHtmlStepUi.js
  package-lock.json
Labels: ready-to-merge

#991 Add spinner while gif is generating
  examples/demo.js
Labels: ready-to-merge

#1007 Gl puppeteer
  CONTRIBUTING.md
  Gruntfile.js
  package-lock.json
  package.json
  src/modules/FisheyeGl/Module.js
  src/modules/_nomodule/gl-context.js
  test/core/modules/benchmark.js
Labels: ready-to-merge

#916 Add a description of the scopeQuery method
  CONTRIBUTING.md
Labels: ready-to-merge

#1019 Fixes crop module bug
  examples/index.html
  examples/lib/defaultHtmlStepUi.js
  package.json
  src/modules/Crop/Crop.js
  src/modules/Crop/Ui.js
  src/modules/Crop/info.json
  test/core/modules/crop.js
Labels: Work In Progress

#667 Refactor: String parsing methods
  src/ImageSequencer.js
  src/Strings.js
Labels: refactoring

#787 Detect and Parse string separated module names
  README.md
  src/ImageSequencer.js
  src/InsertStep.js
  src/ReplaceImage.js
  src/Strings.js
  test/core/modules/image-sequencer.js
Labels: new-feature

#580 Close parenthesis fix
  README.md
  src/Strings.js
Labels: bug

#1024 Fixes Grid-Overlay with node Compatibility
  src/modules/GridOverlay/GridOverlay.js
  src/modules/GridOverlay/Module.js
  src/modules/GridOverlay/info.json
  test/core/modules/gridOverlay.js
Labels: ready-to-merge

#1047 Fixed unresponsive webcam preview window
  examples/index.html
Labels: ready-to-merge
