Repository publiclab/image-sequencer, pull requests merged in 2019-02, with the labels that each got.

#712 Fix choose file option and insert step functionality
  dist/image-sequencer-ui.js
  dist/image-sequencer-ui.min.js
  examples/demo.js
  examples/lib/intermediateHtmlStepUi.js
Labels: needs-rebase, ready-to-merge

#690 Used `pixels.set` To Refactor DrawRectangle
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  src/modules/DrawRectangle/DrawRectangle.js
Labels: needs-rebase, ready-to-merge

#700 Change threshold range
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  src/modules/PaintBucket/PaintBucket.js
  src/modules/PaintBucket/info.json
Labels: needs-rebase, ready-to-merge

#701 Add tint module
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  src/Modules.js
  src/modules/Tint/Module.js
  src/modules/Tint/index.js
  src/modules/Tint/info.json
Labels: needs-rebase, ready-to-merge

#763 Improve Code Quality and Optimize
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  package-lock.json
  package.json
  src/modules/Average/Module.js
  src/modules/Blend/Module.js
  src/modules/Blur/Blur.js
  src/modules/Blur/Module.js
  src/modules/Brightness/Module.js
  src/modules/Channel/Module.js
  src/modules/Colormap/Module.js
  src/modules/Contrast/Contrast.js
  src/modules/Contrast/Module.js
  src/modules/Convolution/Convolution.js
  src/modules/Convolution/Module.js
  src/modules/Dither/Dither.js
  src/modules/GammaCorrection/Module.js
  src/modules/Gradient/Module.js
  src/modules/PaintBucket/Module.js
  src/modules/PaintBucket/PaintBucket.js
  src/modules/Saturation/Module.js
  src/modules/Threshold/Module.js
  src/modules/Threshold/Threshold.js
  src/modules/Tint/Module.js
  src/modules/WhiteBalance/Module.js
  src/modules/_nomodule/PixelManipulation.js
Labels: needs-rebase, ready-to-merge

#777 Add sequencer.getSteps()
  README.md
  package-lock.json
  src/ImageSequencer.js
  test/core/modules/image-sequencer.js
Labels: in progress

#782 Added the resize quick button
  dist/image-sequencer-ui.js
  dist/image-sequencer-ui.min.js
  examples/demo.css
  examples/index.html
  examples/lib/insertPreview.js
  examples/lib/intermediateHtmlStepUi.js
Labels: ready-to-merge

#772 Corrected default view for Saturation module
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  package-lock.json
  src/modules/Saturation/Module.js
Labels: ready-to-merge

#802 Typecast removed
  dist/image-sequencer.js
  dist/image-sequencer.min.js
  src/modules/Brightness/Module.js
  src/modules/PaintBucket/PaintBucket.js
  src/modules/Rotate/Module.js
Labels: needs-rebase, ready-to-merge

#739 Format the "Take a Photo" button
  examples/index.html
Labels: ready-to-merge

#815 Change the style of "improve this tool" button
  examples/index.html
Labels: ready-to-merge
